
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTOR ACTORS ASSOCIATES CASE CASES CLASS COMMA COMPONENT DEPENDS EQUALS EXTENDS GT IDENTIFIER INCLUDE INHERIT INTERFACE LBRACE PACKAGE RBRACE REALIZES SIMPLE SLASH USESprogram : definitions relationsdefinitions : definitions definition\n| definitiondefinition : ACTORS EQUALS LBRACE actors RBRACE\n| CASES EQUALS LBRACE cases RBRACEactors : actors COMMA IDENTIFIER\n| IDENTIFIERcases : cases COMMA IDENTIFIER\n| IDENTIFIERrelations : PACKAGE IDENTIFIER relation_listrelation_list : relation_list relation\n| relationrelation : relation_type source target_participants SLASH GTsource : element_type IDENTIFIERtarget_participants : target_participants element_type IDENTIFIER\n| element_type IDENTIFIERelement_type : CASE\n| ACTOR\n| CLASS\n| COMPONENT\n| INTERFACErelation_type : EXTENDS\n| INCLUDE\n| INHERIT\n| SIMPLE\n| USES\n| REALIZES\n| ASSOCIATES\n| DEPENDS'
    
_lr_action_items = {'ACTORS':([0,2,3,7,37,39,],[4,4,-3,-2,-4,-5,]),'CASES':([0,2,3,7,37,39,],[5,5,-3,-2,-4,-5,]),'$end':([1,6,14,15,29,49,],[0,-1,-10,-12,-11,-13,]),'PACKAGE':([2,3,7,37,39,],[8,-3,-2,-4,-5,]),'EQUALS':([4,5,],[9,10,]),'IDENTIFIER':([8,12,13,31,32,33,34,35,36,38,40,42,47,],[11,26,28,43,-17,-18,-19,-20,-21,44,45,48,50,]),'LBRACE':([9,10,],[12,13,]),'EXTENDS':([11,14,15,29,49,],[17,17,-12,-11,-13,]),'INCLUDE':([11,14,15,29,49,],[18,18,-12,-11,-13,]),'INHERIT':([11,14,15,29,49,],[19,19,-12,-11,-13,]),'SIMPLE':([11,14,15,29,49,],[20,20,-12,-11,-13,]),'USES':([11,14,15,29,49,],[21,21,-12,-11,-13,]),'REALIZES':([11,14,15,29,49,],[22,22,-12,-11,-13,]),'ASSOCIATES':([11,14,15,29,49,],[23,23,-12,-11,-13,]),'DEPENDS':([11,14,15,29,49,],[24,24,-12,-11,-13,]),'CASE':([16,17,18,19,20,21,22,23,24,30,41,43,48,50,],[32,-22,-23,-24,-25,-26,-27,-28,-29,32,32,-14,-16,-15,]),'ACTOR':([16,17,18,19,20,21,22,23,24,30,41,43,48,50,],[33,-22,-23,-24,-25,-26,-27,-28,-29,33,33,-14,-16,-15,]),'CLASS':([16,17,18,19,20,21,22,23,24,30,41,43,48,50,],[34,-22,-23,-24,-25,-26,-27,-28,-29,34,34,-14,-16,-15,]),'COMPONENT':([16,17,18,19,20,21,22,23,24,30,41,43,48,50,],[35,-22,-23,-24,-25,-26,-27,-28,-29,35,35,-14,-16,-15,]),'INTERFACE':([16,17,18,19,20,21,22,23,24,30,41,43,48,50,],[36,-22,-23,-24,-25,-26,-27,-28,-29,36,36,-14,-16,-15,]),'RBRACE':([25,26,27,28,44,45,],[37,-7,39,-9,-6,-8,]),'COMMA':([25,26,27,28,44,45,],[38,-7,40,-9,-6,-8,]),'SLASH':([41,48,50,],[46,-16,-15,]),'GT':([46,],[49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'definitions':([0,],[2,]),'definition':([0,2,],[3,7,]),'relations':([2,],[6,]),'relation_list':([11,],[14,]),'relation':([11,14,],[15,29,]),'relation_type':([11,14,],[16,16,]),'actors':([12,],[25,]),'cases':([13,],[27,]),'source':([16,],[30,]),'element_type':([16,30,41,],[31,42,47,]),'target_participants':([30,],[41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> definitions relations','program',2,'p_program','hython-parser.py',108),
  ('definitions -> definitions definition','definitions',2,'p_definitions','hython-parser.py',112),
  ('definitions -> definition','definitions',1,'p_definitions','hython-parser.py',113),
  ('definition -> ACTORS EQUALS LBRACE actors RBRACE','definition',5,'p_definition','hython-parser.py',120),
  ('definition -> CASES EQUALS LBRACE cases RBRACE','definition',5,'p_definition','hython-parser.py',121),
  ('actors -> actors COMMA IDENTIFIER','actors',3,'p_actors','hython-parser.py',125),
  ('actors -> IDENTIFIER','actors',1,'p_actors','hython-parser.py',126),
  ('cases -> cases COMMA IDENTIFIER','cases',3,'p_cases','hython-parser.py',133),
  ('cases -> IDENTIFIER','cases',1,'p_cases','hython-parser.py',134),
  ('relations -> PACKAGE IDENTIFIER relation_list','relations',3,'p_relations','hython-parser.py',141),
  ('relation_list -> relation_list relation','relation_list',2,'p_relation_list','hython-parser.py',145),
  ('relation_list -> relation','relation_list',1,'p_relation_list','hython-parser.py',146),
  ('relation -> relation_type source target_participants SLASH GT','relation',5,'p_relation','hython-parser.py',153),
  ('source -> element_type IDENTIFIER','source',2,'p_source','hython-parser.py',160),
  ('target_participants -> target_participants element_type IDENTIFIER','target_participants',3,'p_target_participants','hython-parser.py',164),
  ('target_participants -> element_type IDENTIFIER','target_participants',2,'p_target_participants','hython-parser.py',165),
  ('element_type -> CASE','element_type',1,'p_element_type','hython-parser.py',172),
  ('element_type -> ACTOR','element_type',1,'p_element_type','hython-parser.py',173),
  ('element_type -> CLASS','element_type',1,'p_element_type','hython-parser.py',174),
  ('element_type -> COMPONENT','element_type',1,'p_element_type','hython-parser.py',175),
  ('element_type -> INTERFACE','element_type',1,'p_element_type','hython-parser.py',176),
  ('relation_type -> EXTENDS','relation_type',1,'p_relation_type','hython-parser.py',180),
  ('relation_type -> INCLUDE','relation_type',1,'p_relation_type','hython-parser.py',181),
  ('relation_type -> INHERIT','relation_type',1,'p_relation_type','hython-parser.py',182),
  ('relation_type -> SIMPLE','relation_type',1,'p_relation_type','hython-parser.py',183),
  ('relation_type -> USES','relation_type',1,'p_relation_type','hython-parser.py',184),
  ('relation_type -> REALIZES','relation_type',1,'p_relation_type','hython-parser.py',185),
  ('relation_type -> ASSOCIATES','relation_type',1,'p_relation_type','hython-parser.py',186),
  ('relation_type -> DEPENDS','relation_type',1,'p_relation_type','hython-parser.py',187),
]
